### ISSUE TITLE
Dashboard GraphQL endpoint shows 405 error on browser - can't load project list

### ISSUE THREAD

**Issue by mechastorm** [sorry-cypress/charts#219]
## Summary

After installation with Helm, Sorry cypress dashboard loads up but it can't load the project list.

Checking the browser dev tool, it seems to be making a call to "/graphql" but the response returns an NGINX 405 error page.

Was there an additional step to setup that I missed?

## How to reproduce

Install the helm chart with ExternalDNS NGinx enabled on AWS Route53.

Load site after install. 

Ingress Nginx values file

```
  controller:
    service:
      annotations:
        external-dns.alpha.kubernetes.io/hostname: <base-domain>
  service:
    targetPorts:
      http: http
      https: http
    annotations:
      service.beta.kubernetes.io/aws-load-balancer-ssl-cert: <aws acm arn>
      service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "http"
      service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "https"
      service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: '3600'
```

sorry-cypress helm values

```
# All set to default
```

## Environment

- sorry-cypress version: The default that came with the helm chart
- cypress version: The default that came with the helm chart
- helm chart version: `1.13.2`

**Comment by mechastorm** [comment]
I should note that we had set host names on all 3 services (api, dasboard, director). I have also left all other settings by default. I originally assumed it was a CORS issue but according to NGINX, default annotations value would have left CORS origin to be `*` and all other HTTP methods are allowed.

**Comment by lvl162** [comment]
Hi, 
I'm encountering the same problem. Any updates?

**Comment by lvl162** [comment]
Hi @mechastorm,
I was encountering the same problem as yours. 
This is a helm `values.yaml` file showing how I resolved it. Hopefully, it would help. 
```
api:
  ingress:
    hosts:
      - host: your-api-host

dashboard:
  ingress:
    hosts:
      - host: your-dashboard-host
  environmentVariables:
    graphQlSchemaUrl: "http://your-api-host"
```
