### ISSUE TITLE
Use Ingress as S3 Read Proxy

### ISSUE THREAD

**Issue by jhonatanmorais** [sorry-cypress/charts#23]
- [x] I have searched issues for similar feature requests

## What is this feature about (1 sentence)

This feature is about allowing the usage of an `Ingress` resource, combined with a `Service` type `ExternalName`, to expose read access to S3 Bucket through a custom URL (see more about `S3_READ_URL_PREFIX` [here](https://github.com/sorry-cypress/sorry-cypress/pull/53), accessed by user's browser.

## Why is it needed? What is the value? For whom do we build it?

Assuming you want to define a custom URL (based on [`S3_READ_URL_PREFIX`](https://github.com/sorry-cypress/sorry-cypress/pull/53)), allowing read access to S3 Bucket through a private endpoint (VPC network only, for example), you should be able to define it using native K8s resources, as `Ingress` and `Service` to get it done. The approach of using `Service` type `ExternalName` is described in detail on this [Google Cloud Blog post](https://cloud.google.com/blog/products/gcp/kubernetes-best-practices-mapping-external-services). It is a good way to use a [feature provided by sorry-cypress](https://github.com/sorry-cypress/sorry-cypress/pull/53/commits/7b1fa8f2e0d3d4461630fb4e643a0f6694819c3d) without requiring new external infrastructure components.

## High-level feature overview

![sorry-cypress-static ingress](https://i.imgur.com/E5r8iUP.png)

Raw manifests example (using nginx as ingress-controller):

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/upstream-vhost: "<your_bucket_name>.s3-website-<aws_region>.amazonaws.com"
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/cors-allow-origin: ""POST, GET, PUT, DELETE, HEAD"
    kubernetes.io/ingress.class: nginx-aws
  name: sorry-cypress-static
  namespace: sorry-cypress
spec:
  rules:
  - host: <your_bucket_name>.s3-website-<aws_region>.amazonaws.com
    http:
      paths:
      - backend:
          serviceName: sorry-cypress-static
          servicePort: http
        path: /
```
```
apiVersion: v1
kind: Service
metadata:
  name: sorry-cypress-static
  namespace: sorry-cypress
spec:
  externalName: <your_bucket_name>.s3-website-<aws_region>.amazonaws.com
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  type: ExternalName
```

## Other

*NOTE*: If you want to restrict access to your S3 bucket only from your AWS VPC Network, it is recommended creating a Bucket Policy with `aws:SourceVpc` or `aws:SourceVpce` condition keys. More info on [Amazon S3 Condition Keys](https://docs.aws.amazon.com/AmazonS3/latest/dev/amazon-s3-policy-keys.html). To use that is required the creation of a [S3 VPC Endpoint](https://docs.aws.amazon.com/vpc/latest/userguide/vpc-endpoints-s3.html) inside your VPC.
