### ISSUE TITLE
wrong mongodb url

### ISSUE THREAD

**Issue by indreek** [sorry-cypress/charts#62]
## Summary

Cypress-api and cypress-director gets wrong mongodb url: mongodb://cypress-sorry-cypress-mongodb:27017  actual service name is "cypress-mongodb." 

## Environment

- helm chart version: `1.0.3`

**Comment by tico24** [comment]
Can you provide your values? That's certiainly not happening for me on my production system.

There's also already mongodb.mongoConnectionString if you want to change it.

**Comment by indreek** [comment]
Hi

I have installed it with argocd

```
source:
  repoURL: 'https://sorry-cypress.github.io/charts'
  targetRevision: 1.0.3
  helm:
    parameters:
      - name: mongodb.architecture
        value: standalone
      - name: mongodb.mongoConnectionString
        value: 'mongodb://cypress-mongodb:27017'
    values: |
      mongo:
        enabled: true
      director:
        environmentVariables:
          executionDriver: "../execution/mongo/driver"
          dashboardUrl: "https://cypress.xx.xx.xxx/"
          screenshotsDriver: "../screenshots/s3.driver"
        ingress:
          hosts:
            - host: "cypress-director.xx.xx.xxx"
              path: "/"
          annotations:
            cert-manager.io/cluster-issuer: letsencrypt-prod
            kubernetes.io/tls-acme: "true"
            kubernetes.io/ingress.class: nginx-admin
            nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
          tls:
            - hosts:
                - cypress-director.xx.xx.xxx
              secretName: cypress-director-tls
      dashboard:
        environmentVariables:
          graphQlSchemaUrl: "https://cypress.xx.xx.xxx/api"
        ingress:
          hosts:
            - host: "cypress.xx.xx.xxx"
              path: "/"
          annotations:
            cert-manager.io/cluster-issuer: letsencrypt-prod
            kubernetes.io/tls-acme: "true"
            kubernetes.io/ingress.class: nginx-admin
            nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
          tls:
            - hosts:
                - cypress.xx.xx.xxx
              secretName: cypress-tls
      api:
        ingress:
          hosts:
            - host: "cypress.xx.xx.xxx"
              path: "/api"
          annotations:
            cert-manager.io/cluster-issuer: letsencrypt-prod
            kubernetes.io/tls-acme: "true"
            kubernetes.io/ingress.class: nginx-admin
            nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
          tls:
            - hosts:
                - cypress.xx.xx.xxx
              secretName: cypress-tls
      s3:
        bucketName: "xxx"
        region: "xxx"
        ingress:
          hosts:
            - host: "cypress-recordings.xx.xx.xxx"
              path: "/"
          annotations:
            cert-manager.io/cluster-issuer: letsencrypt-prod
            kubernetes.io/tls-acme: "true"
            kubernetes.io/ingress.class: nginx-admin
            nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
          tls:
            - hosts:
                - cypress.recordings.xx.xx.xxx
              secretName: cypress-recordings-tls
  chart: sorry-cypress
```

This is my whole config.
