### ISSUE TITLE
Minio enabled is leading to deployment error

### ISSUE THREAD

**Issue by jkaliaSignify** [sorry-cypress/charts#67]
## Summary
I am using the following for my value.yaml

```
fullnameOverride: "cypress-dashboard"

api:
  image:
    repository: agoldis/sorry-cypress-api
    pullPolicy: Always
  
  enabled: true

  podLabels: 
    label: cypress-api

  ingress:
    labels: {}
    annotations: {}
    hosts:
      - host: cydashapi.local.com
        path: /

dashboard:
  image:
    repository: agoldis/sorry-cypress-dashboard
    pullPolicy: Always
  enabled: true

  environmentVariables:
    graphQlSchemaUrl: "http://cydashapi.local.com/"

  podLabels:
    labels: cypress-dashboard

  ingress:
    enabled: true
    labels: {}
    annotations: {}
    hosts:
      - host: cydashboard.local.com
        path: /
 
director:
  image:
    repository: agoldis/sorry-cypress-director
    pullPolicy: Always
    
  environmentVariables:

    executionDriver: "../execution/mongo/driver"

    screenshotsDriver: "../screenshots/minio.driver"

  podLabels: 
    label: cypress-director

  ingress:
    enabled: true
    labels: {}
    annotations: {}
    hosts:
      - host: cydirector.local.com
        path: /
        
mongodb:
  
  enable: true
  internal_db:
    enabled: true

  persistence:
    # set this to a higher number in deployed envs
    size: 1Gi

minio:
  enabled: true
  service:
    port: "443"

```
- sorry-cypress version: `<here>`
- Cypress package version: 7.7.0
Cypress binary version: 7.7.0
Electron version: 12.0.0-beta.14
Bundled Node version: 14.15.1
- helm chart version: `<here>`
-- version: 1.0.5
-- appVersion: 1.1.0

Error Text

Error: Deployment in version "v1" cannot be handled as a Deployment: v1.Deployment.Spec: v1.DeploymentSpec.Template: v1.PodTemplateSpec.Spec: v1.PodSpec.Containers: []v1.Container: v1.Container.v1.Container.Env: []v1.EnvVar: v1.EnvVar.Value: ReadString: expects " or n, but found 4, error found in #10 byte of ...|,"value":443},{"name|..., bigger context ...|ge.yourdomain.com"},{"name":"MINIO_PORT","value":443},{"name":"MINIO_USESSL","value":"true"}],"image|...
